/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckboxGroup']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
    ButtonView: typeof import('./src/components/Button/ButtonView.vue')['default']
    FileDrop: typeof import('./src/components/file/FileDrop.vue')['default']
    FooterView: typeof import('./src/components/footer/FooterView.vue')['default']
    HeaderView: typeof import('./src/components/header/HeaderView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
  const BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
  const BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
  const BFormCheckbox: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckbox']
  const BFormCheckboxGroup: typeof import('bootstrap-vue-next/components/BFormCheckbox')['BFormCheckboxGroup']
  const BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
  const BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
  const BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
  const BProgress: typeof import('bootstrap-vue-next/components/BProgress')['BProgress']
  const ButtonView: typeof import('./src/components/Button/ButtonView.vue')['default']
  const FileDrop: typeof import('./src/components/file/FileDrop.vue')['default']
  const FooterView: typeof import('./src/components/footer/FooterView.vue')['default']
  const HeaderView: typeof import('./src/components/header/HeaderView.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}