def elaw_data() -> dict[str, str]:
    return {
        "NUMERO_PROCESSO": "",
        "AREA_DIREITO": "",
        "SUBAREA_DIREITO": "",
        "ESTADO": "",
        "COMARCA": "",
        "FORO": "",
        "VARA": "",
        "DATA_DISTRIBUICAO": "",
        "PARTE_CONTRARIA": "",
        "TIPO_PARTE_CONTRARIA": "",
        "DOC_PARTE_CONTRARIA": "",
        "EMPRESA": "",
        "TIPO_EMPRESA": "",
        "DOC_EMPRESA": "",
        "UNIDADE_CONSUMIDORA": "",
        "CAPITAL_INTERIOR": "",
        "DIVISAO": "",
        "ACAO": "",
        "DATA_CITACAO": "",
        "OBJETO": "",
        "PROVIMENTO": "",
        "ADVOGADO_INTERNO": "",
        "ADV_PARTE_CONTRARIA": "",
        "FATO_GERADOR": "",
        "ESCRITORIO_EXTERNO": "",
        "VALOR_CAUSA": "",
        "FASE": "",
    }


def cities_Amazonas() -> dict[str, str]:
    return {
        "Alvarães": "Interior",
        "Amaturá": "Interior",
        "Anamã": "Interior",
        "Anori": "Interior",
        "Apuí": "Interior",
        "Atalaia do Norte": "Interior",
        "Autazes": "Interior",
        "Barcelos": "Interior",
        "Barreirinha": "Interior",
        "Benjamin Constant": "Interior",
        "Beruri": "Interior",
        "Boa Vista do Ramos": "Interior",
        "Boca do Acre": "Interior",
        "Borba": "Interior",
        "Caapiranga": "Interior",
        "Canutama": "Interior",
        "Carauari": "Interior",
        "Careiro": "Interior",
        "Careiro da Várzea": "Interior",
        "Coari": "Interior",
        "Codajás": "Interior",
        "Eirunepé": "Interior",
        "Envira": "Interior",
        "Fonte Boa": "Interior",
        "Guajará": "Interior",
        "Humaitá": "Interior",
        "Ipixuna": "Interior",
        "Iranduba": "Interior",
        "Itacoatiara": "Interior",
        "Itamarati": "Interior",
        "Itapiranga": "Interior",
        "Japurá": "Interior",
        "Juruá": "Interior",
        "Jutaí": "Interior",
        "Lábrea": "Interior",
        "Manacapuru": "Interior",
        "Manaquiri": "Interior",
        "Manaus": "Capital",
        "Manicoré": "Interior",
        "Maraã": "Interior",
        "Maués": "Interior",
        "Nhamundá": "Interior",
        "Nova Olinda do Norte": "Interior",
        "Novo Airão": "Interior",
        "Novo Aripuanã": "Interior",
        "Parintins": "Interior",
        "Pauini": "Interior",
        "Presidente Figueiredo": "Interior",
        "Rio Preto da Eva": "Interior",
        "Santa Isabel do Rio Negro": "Interior",
        "Santo Antônio do Içá": "Interior",
        "São Gabriel da Cachoeira": "Interior",
        "São Paulo de Olivença": "Interior",
        "São Sebastião do Uatumã": "Interior",
        "Silves": "Interior",
        "Tabatinga": "Interior",
        "Tapauá": "Interior",
        "Tefé": "Interior",
        "Tonantins": "Interior",
        "Uarini": "Interior",
        "Urucará": "Interior",
        "Urucurituba": "Interior",
    }
