"""Fornece funcionalidades comuns para o aplicativo CrawJUD.

Este pacote contém módulos utilitários e funções compartilhadas entre
diferentes partes do sistema.
"""

from __future__ import annotations

from typing import NoReturn


def _raise_execution_error(message: str) -> NoReturn:
    from crawjud.common.exceptions.bot import ExecutionError

    raise ExecutionError(message=message)


name_colunas = [
    "NOME_PARTE",
    "PORTAL",
    "FORO",
    "CLASSE",
    "NOME_INTERESSADO",
    "CPF_CNPJ_AUTOR",
    "CPF_CNPJ_REU",
    "VIA_CONDENACAO",
    "TIPO_INTERESSADO",
    "PRAZO_PGTO",
    "AUTOR",
    "REU",
    "TRIBUNAL",
    "COMARCA",
    "VARA",
    "AGENCIA",
    "TIPO_ACAO",
    "VALOR_CALCULADO",
    "TEXTO_DESC",
    "DATA_PGTO",
    "NOME_CUSTOM",
    "TIPO_PROTOCOLO",
    "SUBTIPO_PROTOCOLO",
    "TIPO_ARQUIVO",
    "PETICAO_PRINCIPAL",
    "ANEXOS",
    "TIPO_ANEXOS",
    "TIPO_BUSCA",
    "TERMOS",
    "DATA_FILTRO",
    "QTD_SEQUENCIA",
    "NUMERO_PROCESSO",
    "AREA_DIREITO",
    "SUBAREA_DIREITO",
    "ESTADO",
    "DATA_DISTRIBUICAO",
    "PARTE_CONTRARIA",
    "TIPO_PARTE_CONTRARIA",
    "DOC_PARTE_CONTRARIA",
    "EMPRESA",
    "TIPO_EMPRESA",
    "DOC_EMPRESA",
    "UNIDADE_CONSUMIDORA",
    "CAPITAL_INTERIOR",
    "DIVISAO",
    "ACAO",
    "DATA_CITACAO",
    "OBJETO",
    "PROVIMENTO",
    "ADVOGADO_INTERNO",
    "ADV_PARTE_CONTRARIA",
    "FATO_GERADOR",
    "ESCRITORIO_EXTERNO",
    "VALOR_CAUSA",
    "FASE",
    "PROVISAO",
    "DATA_ATUALIZACAO",
    "VALOR_ATUALIZACAO",
    "OBSERVACAO",
    "TIPO_ANDAMENTO",
    "DATA",
    "OCORRENCIA",
    "OBSERVACAO",
    "ANEXOS",
    "TIPO_ANEXOS",
    "TIPO_GUIA",
    "VALOR_GUIA",
    "DATA_LANCAMENTO",
    "TIPO_PAGAMENTO",
    "SOLICITANTE",
    "TIPO_CONDENACAO",
    "COD_BARRAS",
    "DOC_GUIA",
    "DOC_CALCULO",
    "LOCALIZACAO",
    "CNPJ_FAVORECIDO",
    "PARTE_PETICIONANTE",
    "GRAU",
    "DATA_PUBLICACAO",
    "PALAVRA_CHAVE",
    "TRAZER_DOC",
    "INTIMADO",
    "TRAZER_TEOR",
    "DATA_LIMITE",
    "NOME_MOV",
    "CIDADE_ESTADO",
    "ESFERA",
    "REQUERENTE",
    "REQUERIDO",
    "JUROS_PARTIR",
    "DATA_INCIDENCIA",
    "VALOR_CALCULO",
    "DATA_CALCULO",
    "MULTA_PERCENTUAL",
    "MULTA_DATA",
    "MULTA_VALOR",
    "PERCENT_MULTA_475J",
    "HONORARIO_SUCUMB_PERCENT",
    "HONORARIO_SUCUMB_DATA",
    "HONORARIO_SUCUMB_VALOR",
    "HONORARIO_SUCUMB_PARTIR",
    "JUROS_PERCENT",
    "HONORARIO_CUMPRIMENTO_PERCENT",
    "HONORARIO_CUMPRIMENTO_DATA",
    "HONORARIO_CUMPRIMENTO_VALOR",
    "HONORARIO_CUMPRIMENTO_PARTIR",
    "CUSTAS_DATA",
    "CUSTAS_VALOR",
    "DESC_PAGAMENTO",
    "DESC_OBJETO",
]
